### ISSUE TITLE
Implement the Spring Pet Clinic in Fusion

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/fusion#103]
The Spring Pet Clinic (https://github.com/spring-projects/spring-petclinic) is a sample application that is used by different frameworks to showcase the integration with Spring.

The purpose is to have a full project implementation in Fusion to be used as a reference for current developers, and to raise the awareness of Fusion in the Spring community.

Our internal repository (private for now) is at https://github.com/vaadin/fusion-petclinic

**Comment by gilberto-torrezan** [comment]
@marcushellberg we will need your help for this project.

**Comment by marcushellberg** [comment]
I'd be happy to help. Let me know how. Perhaps we can start off with a quick call to align on what we want to do and decide how to work together?
