### ISSUE TITLE
Support local paths ("file:..." versions) in package.json dependencies

### ISSUE THREAD

**Issue by thron7** [vaadin/fusion#126]
**Is your feature request related to a problem? Please describe.**
When developing an NPM package we want to make sure it works with one or more applications **before** publishing the package to a registry (We often work on an application and a new package in unison). I.e. we want to use an NPM dependency from the app to a local package (usually in another local git repo).

Once the integration is tested, publishing is ok and other devs (and the CI) can use the package happily from the registry. (p)npm supports local paths in dependencies through [`file:`  specifiers](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#local-paths) and package linking - both of which are difficult to use with the Vaadin Spring-Boot server. With a `file:` specifier in package.json's dependencies Vaadin19 would error out ("not a number"), and Vaadin21 hangs forever.

**Describe the solution you'd like**
The frontend spring-boot:run server is parsing package.json to update NPM dependencies. It should support `file:` dependencies and give them priority if the same package is requested through e.g. `@NpmPackage` annotations.

**Describe alternatives you've considered**

- [(p)npm linking](https://pnpm.io/cli/link) is an alternative as it also allows you to engage a local package as NPM dependency, but the Vaadin Spring-Boot server has even more difficulties to detect this, overwrites the dependency in package.json and the subsequent `pnpm install` is then overriding the local link. In short: (p)npm linking is not reliable under Vaadin frontend server.
- Copying the source of the entire NPM package into the source tree of the application. - Works but is darn ugly as it forces you to copy source code between git repos, commiting local changes, until eventually deleting the package source code in the app source again.
- As a fall-back you can always go through publishing your current version of the NPM package to the NPM registry. We have a local NPM registry but this is still an awkward work flow for a developer, publishing intermediate versions just to test them in an application.

**Comment by Artur-** [comment]
Internally these type of URLs are used, do they work?
```
    "@vaadin/application-theme-plugin": "./target/plugins/application-theme-plugin",
```

**Comment by thron7** [comment]
No, I get a 
```
java.lang.NumberFormatException: '../path/to/my/package' is not a valid version!
```

**Comment by thron7** [comment]
Thanks for closing this successfully. What I would like to know, and am unable to infer from the tickets (also looking at flow#12424) - when will this fix be available? Vaadin22? Vaadin23?

**Comment by Artur-** [comment]
It should be in the next Vaadin 22.0 and 23.0 releases
