### ISSUE TITLE
[Fusion] [Form] Binding NumberField to NumberModel produce NaN

### ISSUE THREAD

**Issue by Feuerwerk** [vaadin/fusion#13]
### Description of the bug / feature
When binding a NumberField (vaadin-number-field) to an optional numeric field backed by NumberModel, fill the NumberField with a valid number and then empty it again, you will get an "must be a number" validation error.

### Expected behavior
When clearing the NumberField there should be no validation error when the bound field is optional.
Either NumberModel._fromString or the converter of the field directive (line 117 in Field.js) should return undefined in case of an empty string, so IsNumber-Validator is working correctly for an optional field.

### Actual behavior
NumberModel._fromString currently returns NaN for an empty string. This led to a failing IsNumber-Validator which can neither be removed nor customized.

### Versions:
    - Vaadin / Flow version: 19.0.7

**Comment by Haprog** [comment]
@Feuerwerk Thanks for the detailed ticket! A [fix](https://github.com/vaadin/flow/pull/11169) for this should be in the next release of V20 (and V21 alpha). Probably the fix won't be backported to V19 as this is not a critical issue and V19 won't be supported for long anymore now that V20 is out.
