### ISSUE TITLE
Fusion endpoints do not work after logging in when http.sessionManagement().sessionFixation().migrateSession() is configured

### ISSUE THREAD

**Issue by fluorumlabs** [vaadin/fusion#14]
**Steps to reproduce:**

- Create SVC project
- Create an endpoint with `@AnonymousAllowed` and `@PermitAll` methods
- Follow https://vaadin.com/docs/latest/fusion/security/spring-login docs
- Configure `http.sessionManagement().sessionFixation().migrateSession()` in `SecurityConfig`
- Start the application and make a call to endpoints. Observe that `@AnonymousAllowed` endpoint works, but  `@PermitAll` does not.
- Login
- Call endpoints

**Expected behavior:**

Both endpoints are called and the result is received

**Actual behavior:**

Both `@AnonymousAllowed` and  `@PermitAll` do not work

**Comment by haijian-vaadin** [comment]
Related article https://www.javadevjournal.com/spring-security/spring-security-session-fixation/

**Comment by haijian-vaadin** [comment]
The cause is that the fusion CSRF token in the request is different from the token in the session. [Reuse the Spring CSRF token](https://github.com/vaadin/fusion/issues/12) might solve this problem

**Comment by fluorumlabs** [comment]
I wonder why is it different? Theoretically, `migrateSession()` should copy session attributes to the new session...

**Comment by haijian-vaadin** [comment]
> I wonder why is it different? Theoretically, `migrateSession()` should copy session attributes to the new session...

Yes, I think that's the cause of the problem. The Fusion CSRF token is stored in the session and also the index page (to be used for the request). When copying the attributes from the old session to the newly created session, it also overrides the CSRF token with the old one, which makes the token in the request and the session go out of sync.

**Comment by fluorumlabs** [comment]
Yes, looks like that is the case

**Comment by haijian-vaadin** [comment]
It's fixed by https://github.com/vaadin/flow/issues/10703, since now the CSRF token is no longer stored in the session.
