### ISSUE TITLE
Safari fetches index page from service worker even when online

### ISSUE THREAD

**Issue by Artur-** [vaadin/fusion#22]
### Description of the bug 
When you are online and refresh an application, a new index page should be fetched from the server.

With Safari, a new page is not fetched but the old page from the service worker is used.

### Minimal reproducible example
Open https://labs.vaadin.com/mortgage-calculator/ in Safari
Click on "Apply" - a notification is shown
Refresh
Click on "Apply" - no notification is shown

### Expected behavior
A notification is shown

### Actual behavior
No notification is shown because the CSRF token is missing as the index page is from the service worker. Endpoints do not work as described in #19

### Versions:
    - Vaadin / Fusion version: 19

**Comment by jcgueriaud1** [comment]
It's also affecting vaadin 20.beta3( see #19 for the code )

**Comment by Artur-** [comment]
This is caused by https://github.com/vaadin/flow/blob/master/flow-server/src/main/java/com/vaadin/flow/server/communication/IndexHtmlRequestHandler.java#L190

As no CSRF token is written to the index page when fetched through the service worker, Safari never gets a CSRF token as it fetches the index page through the service worker once it has been installed.

In Vaadin 22, the endpoint CSRF is sent as a cookie so the above case works in 22 alpha 2.
However, login form uses the meta tags written to the page when sending a login request so a start.vaadin.com project using V22 + authentication does not work - you can never log in after refreshing the page

**Comment by haijian-vaadin** [comment]
Close as duplicated to https://github.com/vaadin/fusion/issues/22

**Comment by jcgueriaud1** [comment]
22 is the current ticket. This ticket is a duplicate to which ticket?

**Comment by haijian-vaadin** [comment]
My bad, copy-paste mistake, duplicate with https://github.com/vaadin/fusion/issues/84
