### ISSUE TITLE
Webpack does not respect TypeScript path resolution 

### ISSUE THREAD

**Issue by Lodin** [vaadin/fusion#54]
Typescript can do a path resolution in `tsconfig.json`:
```json
{
  "compilerOptions": {
    "baseUrl": "frontend",
    "paths": {
      "Frontend/*": ["*"],
      "$Generated/*": ["generated/*"]
  }
}
```
However, webpack does not consider that resolution, so it is necessary to support cusom paths with webpack aliases.
```js
{
  resolve: {
    alias: {
      Frontend: path.resolve(__dirname, 'frontend'),
      $Generated: path.resolve(__dirname, 'frontend/generated'),
    }
  }
}
```
As a developer, I would like to specify path resolution in only one place.

## Solution

The better way is to use `TsconfigPathsPlugin` recommended by `ts-loader`. It will do all the aliasing work.
```js
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');

module.exports = {
  ...
  resolve: {
    plugins: [new TsconfigPathsPlugin({ configFile: "./path/to/tsconfig.json" })]
  }
  ...
}
```

**Comment by platosha** [comment]
Reopening this due to revering the fix https://github.com/vaadin/flow/pull/11912
