### ISSUE TITLE
v21.0.0.alpha10 - Generated code results in unfortunate field declarations

### ISSUE THREAD

**Issue by markhm** [vaadin/fusion#58]
Hi team. We've started looking into v21.0.0.alpha10 today and we're intimidated by - what seems to be - the changes to the generated code and the consequence this will have to the state declarations in our views. 

### v20.0.4
Under v20.0.4, the generated code for one of our endpoints looks like this. 

<img width="735" alt="1  v20 0 4" src="https://user-images.githubusercontent.com/1430451/127048391-1a160a1d-beae-4489-a61b-65d11959b131.png">

The corresponding endpoint method looks like this:
```
  @AnonymousAllowed
    public List<SelectedInitiativeResult> getSelectedInitiatives() {
        return selectedInitiativeService.getSelectedInitiatives();
    }
```

### v21.0.0.alpha10
Under v21.0.0.alpha10, the generated code looks like this:

![2  v21 0 0 alpha10](https://user-images.githubusercontent.com/1430451/127048095-29ee8be3-e22e-40d2-957b-eff8656256da.png)

The unfortunate consequence is that our state / field declaration needs to look as is shown in green here (see change vs v20 in red):

<img width="935" alt="3  resulting state declaration in view" src="https://user-images.githubusercontent.com/1430451/127048213-eca974ac-5729-4d39-89cd-677241c615bf.png">

Is this still work in progress or will there be an easier way to declare fields...? 

Many thanks.

**Comment by Lodin** [comment]
Hi @markhm. That's the intended change: we are making the TypeScript output closer to how Java works. To get it back, all you need is to add `@Nonnull` annotation (it can be imported from anywhere; the only requirement is that the non-qualified name should be `nonnull` in case-insensitive format).

So, to generate the previous version of TS, your Java code should look like the following:
```java
@AnonymousAllowed
@Nonnull
public List<@Nonnull SelectedInitiativeResult> getSelectedInitiatives() {
    return selectedInitiativeService.getSelectedInitiatives();
}
```

The documentation for these changes can be found [here](https://vaadin.com/docs/latest/fusion/advanced/endpoints-generator/#type-nullability).

You can also use TS [optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) to handle `undefined` on the client side.

**Comment by markhm** [comment]
Many thanks, @Lodin. This was the clarification we needed. 🙏
