### ISSUE TITLE
Bootstrap page config issue

### ISSUE THREAD

**Issue by roastedcpu** [vaadin/fusion#60]
### Description of the bug / feature
Following the documentation here https://vaadin.com/docs/latest/flow/advanced/modifying-the-bootstrap-page
I should be able to configure the bootstrap page, specifically the page title and the reconnect dialog.

It is not working, none of them change. The only way I'm able to achieve it is by using VaadinServiceInitListener and setting it in a UIInitListener.

### Minimal reproducible example
Starter project v20.0.6
Override configurePage (from AppShellConfigurator) in Application.class:

```
@SpringBootApplication
@Theme(value = "myapp")
@PWA(name = "My App", shortName = "My App", offlineResources = {"images/logo.png"})
@NpmPackage(value = "lumo-css-framework", version = "^4.0.10")
@NpmPackage(value = "line-awesome", version = "1.3.0")
public class Application extends SpringBootServletInitializer implements AppShellConfigurator {

    @Override
    public void configurePage(AppShellSettings settings) {
        settings.setPageTitle("HELLO VAADIN WORLD");
        settings.getReconnectDialogConfiguration().setDialogText("Well, I can't connect right now :(");
    }

    public static void main(String[] args) {
        LaunchUtil.launchBrowserInDevelopmentMode(SpringApplication.run(Application.class, args));
    }

}
```

### Expected behavior
 - By stopping the backend the reload dialog's message should be "Well, I can't connect right now :("
 - The page title should be "HELLO VAADIN WORLD"

### Actual behavior
The default reload dialog's message and the default page title are shown

### Versions:
    - Vaadin / Flow version: 20.0.6
    - Java version: 8/11
    - OS version: MacOS Big Sur v11.2.3 (irrelevant)

**Comment by haijian-vaadin** [comment]
Hi @roastedcpu, do you still remember if it was a Vaadin 20 Flow or Fusion application? Asking because regarding the application title, it works for me for the Flow starter app perfectly fine. For Fusion starter app, there is some code in `index.ts` that updates the title to the default one, which might make it look like that the `settings.setPageTitle("HELLO VAADIN WORLD");` doesn't work.
