### ISSUE TITLE
tsconfig.json overwritten on upgrade to 19.0.7

### ISSUE THREAD

**Issue by markhm** [vaadin/fusion#7]
### Description of the bug 
After our upgrade to 19.0.7, I noticed that our custom `tsconfig.json` was overwritten. 

The first few lines of `tsconfig.json` suggest that modifications will be respected:

```
// This TypeScript configuration file is generated by vaadin-maven-plugin.
// This is needed for TypeScript compiler to compile your TypeScript code in the project.
// It is recommended to commit this file to the VCS.
// You might want to change the configurations to fit your preferences
```

### Minimal reproducible example
Start with v19.0.5 and add the following `compilerOptions`, replacing `paths`:

```
    "paths": {
      "views/*": [ "views/*" ],
      "components/*": [ "components/*" ],
      "routes/*": [ "routes/*" ],
      "store/*": [ "store/*" ],
      "generated/*": [ "generated/*" ],
      "Frontend/*": [
        "*"
      ]
    }
```

Upgrade to 19.0.7 and note that the modifications have disappeared. 

### Expected behavior
Modifications should be respected / left intact. 

### Actual behavior
Modifications have disappeared. 

### Versions:
    - Vaadin / Fusion version: 19.0.5 -> 19.0.7
    - Node version: 16.1.0
    - Java version: 16
    - OS version: macOS latest

**Comment by markhm** [comment]
This problem is probably explained by something else. Closing this one for now.

**Comment by markhm** [comment]
Reopening this one. I thought this issue might have been related to a script we forgot to update. But even after that script was fixed, I just saw again that `tsconfig.json` was not respected. See:

![Screenshot 2021-05-15 at 16 12 13](https://user-images.githubusercontent.com/1430451/118364364-75be6300-b598-11eb-94d9-0f2df77ed0c6.png)

Would be much appreciated if you could look into this.

**Comment by haijian-vaadin** [comment]
Hi @markhm, I wasn't able to reproduce the issue with this project https://github.com/haijian-vaadin/v19-enum-test.
Do you have the `tsconfig.json` file under the project root directory or some other place?
Is it reproducible everytime you run a 19.0.7 project?

**Comment by markhm** [comment]
We have isolated the issue as something not caused by Vaadin, so closing this one.
