### ISSUE TITLE
Endpoints requiring authZ serve HTTP 302 instead of JSON response when user is not logged in

### ISSUE THREAD

**Issue by fluorumlabs** [vaadin/fusion#8]
Steps to reproduce:

```java
@Endpoint
public class RandomEndpoint {
	@PermitAll
	public String permitAllEndpoint() {
		return "permitAll";
	}
}
```

Now, calling `RandomEndpoint.permitAllEndpoint()`, while being non-logged in, results in HTTP 302: redirect to `/login`. This causes `SyntaxError: Unexpected token < in JSON at position 0` on the client side, instead of proper `Error: Endpoint 'RandomEndpoint' method 'permitAllEndpoint' request cannot be accessed, reason: 'Access denied'`

**Comment by haijian-vaadin** [comment]
Could change the Spring security config super class so that for unauthenticated endpoint calls,don't redirect to login, but respond with 401.

**Comment by haijian-vaadin** [comment]
duplicate to https://github.com/vaadin/spring/pull/925
