### ISSUE TITLE
Endpoints stop working in Safari after first refresh

### ISSUE THREAD

**Issue by Artur-** [vaadin/fusion#84]
### Description of the bug 
Endpoints work fine the first time you open an application in Safari.

After refresh, the index page is loaded from the service worker and all endpoint calls fail because of a missing CSRF token. This is reported as "Anonymous access is not allowed" which is misleading in itself.

### Minimal reproducible example
1. Open https://labs.vaadin.com/mortgage-calculator/ in Safari 14.1

The UI shows
```
Monthly payment
1 717,58 € / month
```
and clicking `Apply` shows a notification

2. Refresh the page

### Expected behavior
The UI shows
```
Monthly payment
1 717,58 € / month
```
and clicking `Apply` shows a notification

### Actual behavior
The UI shows
```
Monthly payment
0,00 € / month
```
and clicking `Apply` has no effect.

### Versions:
    - Vaadin / Fusion version: 19, also happens with 21
    - Browser version (if applicable): Mac Safari 14.1

**Comment by Artur-** [comment]
If you remove the service worker manually in the console using e.g.
```
navigator.serviceWorker.getRegistrations().then(function(registrations) {
 for(let registration of registrations) {
  registration.unregister()
} })

```

Then it works on the following refresh

**Comment by fluorumlabs** [comment]
IOS users are also affected

**Comment by haijian-vaadin** [comment]
> IOS users are also affected

Seems it works for me on iPhone with ios 14.7.1

**Comment by fluorumlabs** [comment]
Steps to reproduce on iPhone ios 14.7.1:
1. Navigate to cookbook.vaadin.com
2. Observe that it is loaded correctly
3. Hit "refresh" until it stops showing list of recipes (probably need to wait until workbox cache in all the stuff)

Once you have reached that point, now matter what you do, the web site won't work

**Comment by haijian-vaadin** [comment]
Thanks for the info, indeed I was able to reproduce with cookbook.vaadin.com.
