### ISSUE TITLE
Anonymous endpoints stops working after user logs out in another tab

### ISSUE THREAD

**Issue by fluorumlabs** [vaadin/fusion#9]
Steps to reproduce:

```java
@Endpoint
public class RandomEndpoint {
	@AnonymousAllowed
	public String anonymousEndpoint() {
		return "anonymous";
	}
}
```

1. Open browser and login. 
2. Open a new tab. 
3. Logout in the first tab.

Now, if you call `RandomEndpoint.anonymousEndpoint()` in the second tab, it will return `Error: Endpoint 'RandomEndpoint' method 'anonymousEndpoint' request cannot be accessed, reason: 'Access denied'`). It works properly in the first tab.

**Comment by Legioth** [comment]
I guess this is about the missing mechanism for receiving a CSRF token in the response that says that the provided CSRF token was invalid (or missing).

**Comment by haijian-vaadin** [comment]
Might be fixed by sovling https://github.com/vaadin/flow/issues/10703

**Comment by haijian-vaadin** [comment]
The issue is fixed now. As it now [uses cookie to store the Vaadin CSRF token ](https://github.com/vaadin/flow/issues/10703), also it [reuses Spring CSRF token if available](https://github.com/vaadin/fusion/issues/12).
